lib/mejorarse_web/router.ex
defmodule MejorarseWeb.Router do
  use MejorarseWeb, :router

  import MejorarseWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MejorarseWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController do
      resources "/flashcards", FlashcardController
    end

    # resources "/sessions", SessionController, only: [:create, :delete],
                                              # singleton: true
    post "/sessions", SessionController, :login, singleton: true
    delete "/sessions", SessionController, :logout, singleton: true

  end

  # Other scopes may use custom stacks.
  # scope "/api", MejorarseWeb do
  #   pipe_through :api
  # end
end

lib/mejorarse/accounts/user.ex
defmodule Mejorarse.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Mejorarse.Accounts.Credential
  alias Mejorarse.Accounts


  schema "users" do
    field :name, :string
    field :username, :string
    has_one :credential, Credential

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username])
    |> validate_required([:name, :username])
    |> unique_constraint(:username)
  end

  @doc """
  Get a user either by username or by email. Verify their password.

  """
  def get_and_auth_user(username_or_email, password) do
    user_by_email = Accounts.get_user_by_email(username_or_email)
    user_by_username = Accounts.get_user_by_username(username_or_email)

    require IEx; IEx.pry()

    user =
    cond do
      user_by_username != nil ->
        user_by_username
      user_by_email != nil ->
        user_by_email
      true ->
        nil
    end

    case Comeonin.Argon2.check_pass(user.credential, password) do
      {:ok, _} -> user
      _else       -> nil
    end
  end
end

lib/mejorarse_web/controllers/user_controller.ex
defmodule MejorarseWeb.UserController do
  use MejorarseWeb, :controller

  alias Mejorarse.Accounts
  alias Mejorarse.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    require IEx; IEx.pry()
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        require IEx; IEx.pry()
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/mejorarse_web/views/user_view.ex
defmodule MejorarseWeb.UserView do
  use MejorarseWeb, :view
end

lib/mejorarse_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/mejorarse_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <div class="form-group">
    <%= inputs_for f, :credential, fn cf -> %>

      <%= error_tag cf, :password %>
      <%= label cf, :password, class: "control-label" %>
      <%= password_input cf, :password, class: "form-control" %>

      <%# internally,  we use a password hash, so any errors will be displayed for that tag %>

      <%= error_tag cf, :password_confirmation %>
      <%= label cf, :password_confirmation, class: "control-label" %>
      <%= password_input cf, :password_confirmation, class: "form-control" %>


      <%= label cf, :email %>
      <%= text_input cf, :email %>
      <%= error_tag cf, :email %>
    <% end %>
  </div>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/mejorarse_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user.id), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/mejorarse_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/mejorarse_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.credential.email %>
  </li>

</ul>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user.id) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>
<span><%= link "Flashcards", to: Routes.user_flashcard_path(@conn, :index, @user.id) %></span>